### PR TITLE
[+] TS Connect, Current time [*] Faster reports, only 1 chatreport for multiple bad words

### PR DESCRIPTION
**Pull request by Macoonier**

### CODE REVIEW

**Comment by LukvonStrom** [comment]
well done :+1:

**Comment by LukvonStrom** [comment]
But a delay would be nice, I'm not sure if the server accepts multiple chatreports with no delay

**Comment by Macoonier** [comment]
It is really unlikely that 2 players say a bad word at the same time. I think, however, it is no problem for the server to handle two commands at the same time until you do not spam them in a short delay.

**Comment by LukvonStrom** [comment]
I dunno how permissive the Rewinside Anti Cheat is, but propably 2 Commands that are executed with a very short delay could trigger some sort of punishment.

**Comment by Macoonier** [comment]
I had no problem executing the /chatreport 6 times in a row. I did not receive a punishment.

**Comment by LucaDev** [comment]
Yeah, looks nice, will merge it asap

**Comment by Macoonier** [comment]
Yes it is. I've tested the auto-report function (works) and the teamspeak buttons (works). No exception occurred.

**Comment by Macoonier** [comment]
Do you guys know a way to get all players on the current server? I've only found something for 1.7.X which is outdated (not available anymore).

**Comment by LucaDev** [comment]
What do you need it for?

**Comment by Macoonier** [comment]
It is required for the stats feature (clicking on the name shows the stats) I am able to do that (I've already done that) but I need to check if the player exists. Without checking it you click broadcast messages etc. too and a filter isn't that good (Blacklist all server messages e.g. bedwars, lobby)

**Comment by LucaDev** [comment]
Isnt it possible to check if the nametag belongs to a player? or i.e using the Tablist?

**Comment by Macoonier** [comment]
Well.. if we use the tablist there a problem because what if the player only wants to see staff members?

**Comment by LukvonStrom** [comment]
If the players focus is set to Staffmembers only, the other players aren't sent to the client are they? So this would be an enhancement for the API from @CreepPlays

**Comment by LucaDev** [comment]
Yeah, @AlexDigital is already coding an api for better integrations into rewinside

**Comment by LukvonStrom** [comment]
I knew that and left that comment as a improvement for the api.

**Pull request merged**
